version: '3'
services:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: bookstore
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
    - 3307:3306
    volumes:
      - ./dbdata:/var/lib/mysql
  app:
    build: ./
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/bookstore?createDatabaseIfNotExist=true&useSSL=false
      DB_USER: root
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 8081:8080
    depends_on:
      - database
